const bootScreen=document.getElementById('bootScreen'),bootProgress=document.getElementById('bootProgress'),bootPercent=document.getElementById('bootPercent'),bootLabel=document.getElementById('bootLabel'),app=document.getElementById('app');
let boot=0;const bootWords=['INITIALIZING CORE','LOADING TELEMETRY','VERIFYING ENCRYPTION','CONNECTING TO NODE','SYSTEM READY'];const bootTimer=setInterval(()=>{boot+=Math.floor(Math.random()*15)+8;if(boot>100)boot=100;bootProgress.style.width=boot+'%';bootPercent.textContent=String(boot).padStart(2,'0')+'%';bootLabel.textContent=bootWords[Math.min(Math.floor(boot/25),4)];if(boot===100){clearInterval(bootTimer);setTimeout(()=>{bootScreen.classList.add('done');app.setAttribute('aria-hidden','false');app.classList.add('ready')},450)}},130);
const started=Date.now(),$=s=>document.querySelector(s),logs=$('#logs');let soundOn=false;
const logLines=[['00:00:02','>','Network connection established'],['00:00:04','>','Security check completed'],['00:00:07','>','All systems operational']];function renderLogs(){logs.innerHTML=logLines.slice(-5).map(l=>`<div class="log-entry"><time>${l[0]}</time><span class="log-mark">${l[1]}</span><span>${l[2]}</span></div>`).join('')}renderLogs();
function pad(n){return String(n).padStart(2,'0')}function updateClock(){const d=new Date();$('#clock').innerHTML=`${pad(d.getHours())}:${pad(d.getMinutes())}<span>:${pad(d.getSeconds())}</span>`;$('#date').textContent=d.toLocaleDateString('en-GB',{weekday:'long',day:'2-digit',month:'short',year:'numeric'}).toUpperCase().replace(/,/g,'');const s=Math.floor((Date.now()-started)/1000),u=`${pad(Math.floor(s/3600))}:${pad(Math.floor(s/60)%60)}:${pad(s%60)}`;$('#uptime').textContent=u;$('#heroUptime').textContent=u}setInterval(updateClock,1000);updateClock();
function updateMetrics(){[['cpu',52,84],['memory',43,64],['network',70,94]].forEach(([key,min,max])=>{const card=document.querySelector(`[data-metric=${key}]`),value=Math.floor(min+Math.random()*(max-min));card.querySelector('.metric-value').textContent=value;card.querySelector('.bar i').style.width=value+'%'});$('#latency').textContent=Math.floor(13+Math.random()*16)+'ms'}setInterval(updateMetrics,3000);
const newLogs=['Packet route optimized','Peripheral scan completed','Signal strength recalibrated','Encrypted channel refreshed','Background sync completed','Firewall rules validated'];setInterval(()=>{const d=new Date();logLines.push([`${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`,'>',newLogs[Math.floor(Math.random()*newLogs.length)]]);renderLogs()},7000);
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}$('#clearLogs').onclick=()=>{logLines.splice(0);renderLogs();toast('EVENT STREAM CLEARED')};$('#themeBtn').onclick=()=>{document.body.classList.toggle('theme-violet');document.body.classList.remove('theme-light');toast(document.body.classList.contains('theme-violet')?'VIOLET THEME ACTIVE':'CYAN THEME ACTIVE')};$('#soundBtn').onclick=()=>{soundOn=!soundOn;$('#soundBtn').textContent=soundOn?'◖':'⌁';toast(soundOn?'AUDIO FEEDBACK ON':'AUDIO FEEDBACK OFF')};$('#fullscreenBtn').onclick=()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.()};
const commands={help:'commands: status, clear, theme, fullscreen, reboot',status:'all systems operational / node 07 online',clear:'event stream cleared',theme:'use the palette button to cycle themes',fullscreen:'fullscreen toggled'};$('#terminalForm').onsubmit=e=>{e.preventDefault();const input=$('#terminalInput'),cmd=input.value.trim().toLowerCase();if(!cmd)return;const out=$('#terminalOutput');out.innerHTML+=`<p><i>nova@system</i>:~$ ${cmd}</p><p class="${cmd==='status'?'success':''}">${commands[cmd]||'command not found — try “help”'}</p><p><i>nova@system</i>:~$ <span class="cursor"></span></p>`;input.value='';out.scrollTop=out.scrollHeight;if(cmd==='clear'){$('#clearLogs').click()}if(cmd==='fullscreen')$('#fullscreenBtn').click()};document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='h'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName))toast('SHORTCUTS: F fullscreen · T theme · S sound · / terminal');if(e.key.toLowerCase()==='f')$('#fullscreenBtn').click();if(e.key.toLowerCase()==='t')$('#themeBtn').click();if(e.key.toLowerCase()==='s')$('#soundBtn').click();if(e.key==='/'){e.preventDefault();$('#terminalInput').focus()}});
